Return-Path: <linux-unionfs-owner@vger.kernel.org>
X-Original-To: lists+linux-unionfs@lfdr.de
Delivered-To: lists+linux-unionfs@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id EC18F75EDA7
	for <lists+linux-unionfs@lfdr.de>; Mon, 24 Jul 2023 10:32:06 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S230062AbjGXIcF (ORCPT <rfc822;lists+linux-unionfs@lfdr.de>);
        Mon, 24 Jul 2023 04:32:05 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:60502 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S231550AbjGXIcE (ORCPT
        <rfc822;linux-unionfs@vger.kernel.org>);
        Mon, 24 Jul 2023 04:32:04 -0400
Received: from mail-oa1-f69.google.com (mail-oa1-f69.google.com [209.85.160.69])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id ABC6294
        for <linux-unionfs@vger.kernel.org>; Mon, 24 Jul 2023 01:31:57 -0700 (PDT)
Received: by mail-oa1-f69.google.com with SMTP id 586e51a60fabf-1bb5d553d19so1968806fac.3
        for <linux-unionfs@vger.kernel.org>; Mon, 24 Jul 2023 01:31:57 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20221208; t=1690187517; x=1690792317;
        h=to:from:subject:message-id:date:mime-version:x-gm-message-state
         :from:to:cc:subject:date:message-id:reply-to;
        bh=5J7ktKzhmZkgZE+x3/G0qL4ztdEtmMYBnbiSBN9PzD4=;
        b=e0oTxcwDPFpVbtVg+WiDzALExzf6GMW0SmJt4x3qyBCmlYk8CUhza2EK+CHVZu5FbX
         IielXxZmpvl3tDGEiz4/+XGsE/o9lniKrOXaiAbTfM61xhIDV6ckwn8uJrMtN4XzbiCX
         HCFIp4TSzgOPz7fazxg4eyhGu0U8zcp9Ig98Jlh1+EVCMDdAh1NMvSSsnCoKruJ+jlMu
         IAGydjwQ6OdU+c7Yi3WCiSZOn8hjl6Zq4gLJTXrTAUhosqKaSWZvaSxICCyKFabQqWv1
         qI8zBqq2Qu3YRNNJFocszOtjoFXCHtwiC4MGlmdqo24dM6CJW4gHN+YUyJcbv84JKJVh
         /Zcg==
X-Gm-Message-State: ABy/qLb1V9tSMPHsca43fX9G+wVoNm689ySkOfH+B785uGUM5UPtwAxz
        MC4++kxOyKTlaHqS/R/eRpX6C6B4RHI+NQhcOhR2Ps/61gIP
X-Google-Smtp-Source: APBJJlGj/AJV4crgXsUXx9xg+t5bD9FjXzISucJ6nztTudvcQmIAzJBWyVunO9vhiMzwYzSXUNaEEibrpyrJIIYrloS6X308afx3
MIME-Version: 1.0
X-Received: by 2002:a05:6870:5b1b:b0:1bb:785d:7436 with SMTP id
 ds27-20020a0568705b1b00b001bb785d7436mr1599528oab.10.1690187517019; Mon, 24
 Jul 2023 01:31:57 -0700 (PDT)
Date:   Mon, 24 Jul 2023 01:31:56 -0700
X-Google-Appengine-App-Id: s~syzkaller
X-Google-Appengine-App-Id-Alias: syzkaller
Message-ID: <0000000000008e4e370601377210@google.com>
Subject: [syzbot] Monthly overlayfs report (Jul 2023)
From:   syzbot <syzbot+lista7343adf220a77c2e87e@syzkaller.appspotmail.com>
To:     linux-fsdevel@vger.kernel.org, linux-kernel@vger.kernel.org,
        linux-unionfs@vger.kernel.org, miklos@szeredi.hu,
        syzkaller-bugs@googlegroups.com
Content-Type: text/plain; charset="UTF-8"
X-Spam-Status: No, score=-1.7 required=5.0 tests=BAYES_00,FROM_LOCAL_HEX,
        HEADER_FROM_DIFFERENT_DOMAINS,RCVD_IN_DNSWL_NONE,RCVD_IN_MSPIKE_H3,
        RCVD_IN_MSPIKE_WL,SPF_HELO_NONE,SPF_PASS,T_SCC_BODY_TEXT_LINE
        autolearn=no autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <linux-unionfs.vger.kernel.org>
X-Mailing-List: linux-unionfs@vger.kernel.org

Hello overlayfs maintainers/developers,

This is a 31-day syzbot report for the overlayfs subsystem.
All related reports/information can be found at:
https://syzkaller.appspot.com/upstream/s/overlayfs

During the period, 3 new issues were detected and 1 were fixed.
In total, 7 issues are still open and 18 have been fixed so far.

Some of the still happening issues:

Ref Crashes Repro Title
<1> 727     Yes   possible deadlock in mnt_want_write (2)
                  https://syzkaller.appspot.com/bug?extid=b42fe626038981fb7bfa
<2> 50      No    general protection fault in d_path
                  https://syzkaller.appspot.com/bug?extid=a67fc5321ffb4b311c98
<3> 5       No    possible deadlock in seq_read_iter (2)
                  https://syzkaller.appspot.com/bug?extid=da4f9f61f96525c62cc7

---
This report is generated by a bot. It may contain errors.
See https://goo.gl/tpsmEJ for more information about syzbot.
syzbot engineers can be reached at syzkaller@googlegroups.com.

To disable reminders for individual bugs, reply with the following command:
#syz set <Ref> no-reminders

To change bug's subsystems, reply with:
#syz set <Ref> subsystems: new-subsystem

You may send multiple commands in a single email message.
